# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZHCXFaaH7BOywJjP86YcUqb19nbN7XUq
"""

# pip install pyTelegramBotAPI

import telebot # telebot для начала
token = '1706546567:AAEuglIh-gcmU8KnP3hebhjPUwkx5qUj3cg'


bot = telebot.TeleBot(token) # создаем бота

@bot.message_handler(content_types=["text"])
def repeat_all_messages(message): # Название функции не играет никакой роли, в принципе
    bot.send_message(message.chat.id, message.text)


bot.infinity_polling()

