# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iXLKnf4fXhMSM9rIAyBLtmEBeA8GWKPe
"""



pip install pyTelegramBotAPI

import telebot
token = '1202446143:AAHFPF0fvtaRLToU40VSRIoDoWwdR-ikmZM'
import random
devizions = ["Ozon Top" , "Как же я люблю Ozon", "Всегда заказываю только на Ozon"]

bot = telebot.TeleBot(token)

@bot.message_handler(content_types=["text"])
def repeat_ozon_message(message): # Название функции не играет никакой роли, в принципе
  if message.text == "Ozon":
    message.text= random.choice(devizions)
    bot.send_message(message.chat.id,  message.text)


bot.infinity_polling()